name: benkyo
description: A japanese learning app.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter_screenutil: ^5.0.0+2
  shared_preferences: ^2.0.13
  websafe_svg: ^2.1.1
  get: ^4.3.8
  flutter:
    sdk: flutter
  home_indicator: ^2.0.2

  cupertino_icons: ^1.0.2
  flutter_launcher_icons_maker: "^0.10.1"
  flutter_native_splash: ^2.1.1
  flutter_local_notifications: ^9.4.0
  drift: ^1.5.0
  path_provider: ^2.0.9
  sqlite3_flutter_libs: ^0.5.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/勉強-logos.jpeg"

dev_dependencies:
  drift_dev: ^1.5.2
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_native_splash:
  color: "#121421"
  image: assets/splash_screen/勉強-logos.png
  branding: assets/splash_screen/Benkyō-logos.png
  branding_mode: bottom
  android: true
  ios: true